#!/bin/bash
DIR="$(cd "$(dirname $0)" && pwd)"
if [ -d $DIR/backup/.cinnamon ];then
	printf "Theme is aldready installed, exiting now."
	exit 0
fi

if [ -f /usr/bin/cinnamon ];then
	echo creating backup...
	echo -n false >$DIR/backup/uninstallcinnamon
	mv ~/.local/share/cinnamon/ $DIR/backup/.local/share/
	mv ~/.cinnamon/ $DIR/backup/
	cp -r ~/.icons $DIR/backup
	gsettings list-recursively | grep cinnamon >>$DIR/backup/gsettings
else
	echo installing cinnamon...
	sudo apt update
	sudo apt install cinnamon -y
	echo -n true >$DIR/backup/uninstallcinnamon
fi
mkdir -p ~/.local/share/backgrounds

cp -r $DIR/HOME/.cinnamon/ ~/
cp -r $DIR/HOME/.local/ ~/
cp -r $DIR/HOME/.config/ ~/
cp -r $DIR/HOME/.icons/ ~/
echo $HOME/.local/share/backgrounds >~/.cinnamon/backgrounds/user-folders.lst
if [ "$(uname -m)" == "x86_64" ];then
	if [ ! -f /usr/bin/microsoft-edge-dev ];then
		echo true >"$DIR/backup/uninstmicrosoft-edge"
		echo Installing Microsoft Edge
		## Setup
		wget https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add
		sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ 2>&1 >/dev/null
		sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
		sudo rm microsoft.gpg
		## Install
		sudo apt update 2>$DIR/errors | while read line;do printf "\r" ; printf "$line                                         " ;done; printf "\r"; cat $DIR/errors
		sudo apt install microsoft-edge-dev2>$DIR/errors | while read line;do printf "\r" ; printf "$line                                         " ;done; printf "\r"; cat $DIR/errors
	fi
else
	echo "[Desktop Entry]
Version=1.0
Name=Microsoft Edge
# Only KDE 4 seems to use GenericName, so we reuse the KDE strings.
# From Ubuntu's language-pack-kde-XX-base packages, version 9.04-20090413.
GenericName=Web Browser
GenericName[ar]=متصفح الشبكة
GenericName[bg]=Уеб браузър
GenericName[ca]=Navegador web
GenericName[cs]=WWW prohlížeč
GenericName[da]=Browser
GenericName[de]=Web-Browser
GenericName[el]=Περιηγητής ιστού
GenericName[en_GB]=Web Browser
GenericName[es]=Navegador web
GenericName[et]=Veebibrauser
GenericName[fi]=WWW-selain
GenericName[fr]=Navigateur Web
GenericName[gu]=વેબ બ્રાઉઝર
GenericName[he]=דפדפן אינטרנט
GenericName[hi]=वेब ब्राउज़र
GenericName[hu]=Webböngésző
GenericName[it]=Browser Web
GenericName[ja]=ウェブブラウザ
GenericName[kn]=ಜಾಲ ವೀಕ್ಷಕ
GenericName[ko]=웹 브라우저
GenericName[lt]=Žiniatinklio naršyklė
GenericName[lv]=Tīmekļa pārlūks
GenericName[ml]=വെബ് ബ്രൌസര്‍
GenericName[mr]=वेब ब्राऊजर
GenericName[nb]=Nettleser
GenericName[nl]=Webbrowser
GenericName[pl]=Przeglądarka WWW
GenericName[pt]=Navegador Web
GenericName[pt_BR]=Navegador da Internet
GenericName[ro]=Navigator de Internet
GenericName[ru]=Веб-браузер
GenericName[sl]=Spletni brskalnik
GenericName[sv]=Webbläsare
GenericName[ta]=இணைய உலாவி
GenericName[th]=เว็บเบราว์เซอร์
GenericName[tr]=Web Tarayıcı
GenericName[uk]=Навігатор Тенет
GenericName[zh_CN]=网页浏览器
GenericName[zh_HK]=網頁瀏覽器
GenericName[zh_TW]=網頁瀏覽器
# Not translated in KDE, from Epiphany 2.26.1-0ubuntu1.
GenericName[bn]=ওয়েব ব্রাউজার
GenericName[fil]=Web Browser
GenericName[hr]=Web preglednik
GenericName[id]=Browser Web
GenericName[or]=ଓ୍ବେବ ବ୍ରାଉଜର
GenericName[sk]=WWW prehliadač
GenericName[sr]=Интернет прегледник
GenericName[te]=మహాతల అన్వేషి
GenericName[vi]=Bộ duyệt Web
# Gnome and KDE 3 uses Comment.
Comment=Access the Internet
Comment[ar]=الدخول إلى الإنترنت
Comment[bg]=Достъп до интернет
Comment[bn]=ইন্টারনেটটি অ্যাক্সেস করুন
Comment[ca]=Accedeix a Internet
Comment[cs]=Přístup k internetu
Comment[da]=Få adgang til internettet
Comment[de]=Internetzugriff
Comment[el]=Πρόσβαση στο Διαδίκτυο
Comment[en_GB]=Access the Internet
Comment[es]=Accede a Internet.
Comment[et]=Pääs Internetti
Comment[fi]=Käytä internetiä
Comment[fil]=I-access ang Internet
Comment[fr]=Accéder à Internet
Comment[gu]=ઇંટરનેટ ઍક્સેસ કરો
Comment[he]=גישה אל האינטרנט
Comment[hi]=इंटरनेट तक पहुंच स्थापित करें
Comment[hr]=Pristup Internetu
Comment[hu]=Internetelérés
Comment[id]=Akses Internet
Comment[it]=Accesso a Internet
Comment[ja]=インターネットにアクセス
Comment[kn]=ಇಂಟರ್ನೆಟ್ ಅನ್ನು ಪ್ರವೇಶಿಸಿ
Comment[ko]=인터넷 연결
Comment[lt]=Interneto prieiga
Comment[lv]=Piekļūt internetam
Comment[ml]=ഇന്റര്‍‌നെറ്റ് ആക്‌സസ് ചെയ്യുക
Comment[mr]=इंटरनेटमध्ये प्रवेश करा
Comment[nb]=Gå til Internett
Comment[nl]=Verbinding maken met internet
Comment[or]=ଇଣ୍ଟର୍ନେଟ୍ ପ୍ରବେଶ କରନ୍ତୁ
Comment[pl]=Skorzystaj z internetu
Comment[pt]=Aceder à Internet
Comment[pt_BR]=Acessar a internet
Comment[ro]=Accesaţi Internetul
Comment[ru]=Доступ в Интернет
Comment[sk]=Prístup do siete Internet
Comment[sl]=Dostop do interneta
Comment[sr]=Приступите Интернету
Comment[sv]=Gå ut på Internet
Comment[ta]=இணையத்தை அணுகுதல்
Comment[te]=ఇంటర్నెట్‌ను ఆక్సెస్ చెయ్యండి
Comment[th]=เข้าถึงอินเทอร์เน็ต
Comment[tr]=İnternet'e erişin
Comment[uk]=Доступ до Інтернету
Comment[vi]=Truy cập Internet
Comment[zh_CN]=访问互联网
Comment[zh_HK]=連線到網際網路
Comment[zh_TW]=連線到網際網路
Exec=x-www-browser
StartupNotify=true
Terminal=false
Icon=edge.png
Type=Application
Categories=Network;WebBrowser;
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/ftp;x-scheme-handler/http;x-scheme-handler/https;
">~/.local/share/applications/microsoft-edge-dev.desktop
fi
sudo cp -r $DIR/themes/. /.
echo configuring splashscreen...
sudo chmod +x /usr/share/plymouth/themes/win10/install-as-root.sh && sudo bash /usr/share/plymouth/themes/win10/install-as-root.sh
echo setting cinnamon ...
cd $DIR/cursor
sudo rm -rf /usr/share/icons/Win-10 && sudo cp -rf Win-8.1-S/ /usr/share/icons/Win-10 && sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/Win-10/cursor.theme 90 && sudo update-alternatives --set x-cursor-theme /usr/share/icons/Win-10/cursor.theme
cp /usr/share/icons/default/index.theme ~/.icons/default/
$DIR/reconfigure $DIR/settings
echo "[Desktop Entry]
Type=Application
Name=Windows-10
Exec=$HOME/.cinnamon/startup" >~/.config/autostart/win10.desktop
chmod +x $HOME/.cinnamon/startup
bash -c "cinnamon-launcher &>/dev/null &"
