#!/bin/bash
DIR="$(cd "$(dirname $0)" && pwd)"
if [ ! -f /usr/bin/cinnamon ];then
	echo installing cinnamon...
	sudo apt install cinnamon -y
fi
mkdir -p ~/.local/share/backgrounds
echo $HOME/.local/share/backgrounds >~/.cinnamon/backgrounds/user-folders.lst
cp -r $DIR/HOME/.cinnamon/ ~/
cp -r $DIR/HOME/.local/ ~/
cp -r $DIR/HOME/.config/ ~/
cp -r $DIR/HOME/.icons/ ~/
sudo cp -r $DIR/themes/. /.
echo configuring splashscreen...
sudo chmod +x /usr/share/plymouth/themes/win10/install-as-root.sh && sudo bash /usr/share/plymouth/themes/win10/install-as-root.sh
echo setting cinnamon ...
gsettings set org.cinnamon.desktop.interface gtk-theme Windows-10
gsettings set org.cinnamon.theme name Windows-10
gsettings set org.cinnamon.desktop.wm.preferences theme Windows-10
gsettings set org.cinnamon.desktop.interface icon-theme Windows-10-icons
cd $DIR/cursor
sudo cp -rf Win-8.1-NS/ /usr/share/icons/Win-10 && sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/Win-8.1-NS/cursor.theme 90 && sudo update-alternatives --set x-cursor-theme /usr/share/icons/Win-8.1-NS/cursor.theme
cp /usr/share/icons/default/index.theme ~/.icons/default/
gsettings set org.cinnamon.desktop.interface cursor-theme Win-10
chmod +x $DIR/onstartup
cp $DIR/onstartup ~/.config/autostart
echo reboot to use this theme
