#!/bin/bash
DIR="$(cd "$(dirname $0)" && pwd)"
if [ -d $DIR/backup/.cinnamon ];then
	printf "Theme is aldready installed, exiting now."
	exit 0
fi
if [ -f /usr/bin/cinnamon ];then
	echo creating backup...
	echo -n false >$DIR/backup/uninstallcinnamon
	mv ~/.local/share/cinnamon/ $DIR/backup/.local/share/
	mv ~/.cinnamon/ $DIR/backup/
	cp -r ~/.icons $DIR/backup
	printf "set org.cinnamon.desktop.interface gtk-theme ">$DIR/backup/gsettings
	gsettings get org.cinnamon.desktop.interface gtk-theme>>$DIR/backup/gsettings
	printf "set org.cinnamon.theme name ">>$DIR/backup/gsettings
	gsettings get org.cinnamon.theme name>>$DIR/backup/gsettings
	printf "set org.cinnamon.desktop.wm.preferences theme ">>$DIR/backup/gsettings
	gsettings get org.cinnamon.desktop.wm.preferences theme>>$DIR/backup/gsettings
	printf "set org.cinnamon.desktop.interface icon-theme ">>$DIR/backup/gsettings
	gsettings get org.cinnamon.desktop.interface icon-theme>>$DIR/backup/gsettings
	printf "set org.cinnamon.desktop.background picture-uri ">>$DIR/backup/gsettings
	gsettings get org.cinnamon.desktop.background picture-uri >>$DIR/backup/gsettings
	printf "set org.cinnamon.desktop.interface cursor-theme ">>$DIR/backup/gsettings
	gsettings get org.cinnamon.desktop.interface cursor-theme>>$DIR/backup/gsettings
else
	echo installing cinnamon...
	sudo apt update
	sudo apt install cinnamon -y
	echo -n true >$DIR/backup/uninstallcinnamon
fi
mkdir -p ~/.local/share/backgrounds

cp -r $DIR/HOME/.cinnamon/ ~/
cp -r $DIR/HOME/.local/ ~/
cp -r $DIR/HOME/.config/ ~/
cp -r $DIR/HOME/.icons/ ~/
echo $HOME/.local/share/backgrounds >~/.cinnamon/backgrounds/user-folders.lst
sudo cp -r $DIR/themes/. /.
echo configuring splashscreen...
sudo chmod +x /usr/share/plymouth/themes/win10/install-as-root.sh && sudo bash /usr/share/plymouth/themes/win10/install-as-root.sh
echo setting cinnamon ...
gsettings set org.cinnamon.desktop.interface gtk-theme Windows-10
gsettings set org.cinnamon.theme name Windows-10
gsettings set org.cinnamon.desktop.wm.preferences theme Windows-10
gsettings set org.cinnamon.desktop.interface icon-theme Windows-10
gsettings set org.cinnamon.desktop.background picture-uri  'file:///'"$HOME/.local/share/backgrounds/Windows10.jpg"

gsettings set org.cinnamon panel-launchers "['DEPRECATED']"
gsettings set org.cinnamon panel-zone-text-sizes "'[{\"panelId\": 1, \"left\":0.0, \"center\":0.0, \"right\":0.0}]'"
gsettings set org.cinnamon panel-zone-symbolic-icon-sizes "'[{\"panelId\": 1, \"left\": 28, \"center\": 28, \"right\": 16}]'"
gsettings set org.cinnamon panels-enabled "['1:0:bottom']"
gsettings set org.cinnamon panel-launchers-draggable true
gsettings set org.cinnamon panel-scale-text-icons false
gsettings set org.cinnamon panels-autohide "['1:false']"
gsettings set org.cinnamon panels-height "['1:40']"
gsettings set org.cinnamon panels-hide-delay "['1:0']"
gsettings set org.cinnamon no-adjacent-panel-barriers false
gsettings set org.cinnamon panels-show-delay "['1:0']"
gsettings set org.cinnamon panel-zone-icon-sizes "'[{\"panelId\": 1, \"left\": 0, \"center\": 0, \"right\": 24}]'"
gsettings set org.cinnamon panel-edit-mode false
gsettings set org.cinnamon enabled-applets "['panel1:left:1:menu@cinnamon.org:0', 'panel1:left:3:grouped-window-list@cinnamon.org:2', 'panel1:right:4:systray@cinnamon.org:3', 'panel1:right:5:xapp-status@cinnamon.org:4', 'panel1:right:6:notifications@cinnamon.org:5', 'panel1:right:7:printers@cinnamon.org:6', 'panel1:right:8:removable-drives@cinnamon.org:7', 'panel1:right:9:keyboard@cinnamon.org:8', 'panel1:right:10:network@cinnamon.org:9', 'panel1:right:11:sound@cinnamon.org:10', 'panel1:right:12:power@cinnamon.org:11', 'panel1:right:14:clean-show-desktop@filipetorresbr:19', 'panel1:right:13:calendar@cinnamon.org:12']"
cd $DIR/cursor
sudo cp -rf Win-8.1-NS/ /usr/share/icons/Win-10 && sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/Win-10/cursor.theme 90 && sudo update-alternatives --set x-cursor-theme /usr/share/icons/Win-10/cursor.theme
cp /usr/share/icons/default/index.theme ~/.icons/default/
gsettings set org.cinnamon.desktop.interface cursor-theme Win-10
echo "[Desktop Entry]
Type=Application
Name=Windows-10
Exec=$HOME/.cinnamon/startup" >~/.config/autostart/win10.desktop
bash -c "cinnamon-launcher &>/dev/null &"
